"""Add upload, message, and persona models

Revision ID: 8ea0eb234966
Revises: 821f22003bb0
Create Date: 2026-04-29 22:29:36.865844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ea0eb234966'
down_revision: Union[str, None] = '821f22003bb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploads',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.Enum('WHATSAPP', 'INSTAGRAM', 'TELEGRAM', name='uploadsource'), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'PARSING', 'COMPLETED', 'FAILED', name='uploadstatus'), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploads_status'), 'uploads', ['status'], unique=False)
    op.create_index(op.f('ix_uploads_user_id'), 'uploads', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sender', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_media', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_sender'), 'messages', ['sender'], unique=False)
    op.create_index(op.f('ix_messages_timestamp'), 'messages', ['timestamp'], unique=False)
    op.create_index(op.f('ix_messages_upload_id'), 'messages', ['upload_id'], unique=False)
    op.create_table('personas',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('age_range', sa.String(length=32), nullable=False),
    sa.Column('voice_signature', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('themes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('beliefs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fears', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('relationships', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sample_messages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('EXTRACTING', 'READY', 'FAILED', name='personastatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personas_status'), 'personas', ['status'], unique=False)
    op.create_index(op.f('ix_personas_upload_id'), 'personas', ['upload_id'], unique=False)
    op.create_index(op.f('ix_personas_user_id'), 'personas', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_personas_user_id'), table_name='personas')
    op.drop_index(op.f('ix_personas_upload_id'), table_name='personas')
    op.drop_index(op.f('ix_personas_status'), table_name='personas')
    op.drop_table('personas')
    op.drop_index(op.f('ix_messages_upload_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_timestamp'), table_name='messages')
    op.drop_index(op.f('ix_messages_sender'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_uploads_user_id'), table_name='uploads')
    op.drop_index(op.f('ix_uploads_status'), table_name='uploads')
    op.drop_table('uploads')
    # ### end Alembic commands ###
